image: registry.gitlab.com/byacrates/hoy

stages:
  - test
  - coverage

variables:
  PACKAGE_VERSION: "${CI_COMMIT_TAG}"
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/crates/${PACKAGE_VERSION}"

test:
  stage: test
  artifatcs:
    paths:
      - coverage/
      - release/package/
  script:
    - echo "Running tests..."
    - mkdir -p release/package
    - just ci
    - |
      if [-n "${CI_COMMIT_TAG}"]; then
        echo "Packaging hoy..."
        just package
        rm -rf relases/package/tmp-crate
      fi

coverage:
  stage: coverage
  image: curlimages/curl:latest
  needs:
    - job: test
  dependencies:
    - test
  script:
    - echo "Uploading coverage reports"
    - curl -L https://github.com/coverallsapp/coverage-reporter/releases/latest/download/coveralls-linux-x86_64.tar.gz | tar -xz
    - chmod +x ./coveralls
    - ./coveralls report coverage/lcov.info --repo-token "${COVERALLS_TOKEN}"
