[workspace]
members = [
    ".",
    "lib/core",
    "lib/net",
    "lib/protocol",
    "lib/tui",
]

[package]
name = "hoy"
version = "0.0.0-r3"
authors = ["mrbya <v.toth.svk2@gmail.com>"]
edition = "2024"
rust-version = "1.85.0"
description = "Real-time messaging TUI app"
# documentation = ""
homepage = "https://gitlab.com/byacrates/hoy.git"
repository = "https://gitlab.com/byacrates/hoy.git"
license = "MIT OR Apache-2.0"
keywords = ["hoy", "chat"]
categories = ["command-line-utilities"]

publish = true

[[bin]]
name = "hoy"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
hoy-core = { version = "0.0.0" }
hoy-net = { version = "0.0.0" }
hoy-protocol = { version = "0.0.0" }
hoy-tui = { version = "0.0.0" }

[dev-dependencies]
criterion = "0.8"
pretty_assertions = "1"

[package.metadata.cargo-udeps.ignore]
development = ["criterion", "pretty_assertions"]

[package.metadata.playground]
features = ["full"]

[profile.release]
codegen-units = 1
incremental = false

[profile.bench]
codegen-units = 1
incremental = false

[lints.clippy]
multiple_crate_versions = "allow"

[[bench]]
name = "benches"
harness = false
required-features = ["full"]
